# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js 18 base image
FROM node:18-slim AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the project
RUN npm run build

# Prepare the release image
FROM node:18-slim AS release

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder image
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json /app/node_modules /app/

# Expose any necessary ports (if needed)
# EXPOSE <port_number>

# Set the entrypoint to run the MCP server
ENTRYPOINT ["node", "dist/index.js"]
